import { NextResponse } from "next/server";
import * as XLSX from "xlsx";
import { createAdminClient } from "@/lib/supabase/admin";
function text(r:any,n:string[]){for(const k of n){if(r[k]!==undefined&&String(r[k]).trim()!=="")return String(r[k]).trim()}return ""}
export async function POST(request:Request){
 try{const form=await request.formData();const file=form.get("file");const role=String(form.get("actorRole")??"");if(!["admin","super_admin"].includes(role))return NextResponse.json({error:"เฉพาะแอดมินเท่านั้น"},{status:403});if(!(file instanceof File))return NextResponse.json({error:"กรุณาเลือกไฟล์"},{status:400});
 const wb=XLSX.read(Buffer.from(await file.arrayBuffer()),{type:"buffer",cellDates:true});const rows=XLSX.utils.sheet_to_json<any>(wb.Sheets[wb.SheetNames[0]],{defval:""});const s=createAdminClient();let created=0,updated=0,errors:any[]=[];
 for(let i=0;i<rows.length;i++){const r=rows[i];try{const sku=text(r,["SKU","sku"]),category=text(r,["Category","category","หมวดหมู่"]),model=text(r,["Model Name","model_name","ชื่อรุ่น"]),color=text(r,["Color","color","สี"]),power=text(r,["Power","power","ค่าสายตา"]),productType=text(r,["Product Type","product_type","ชนิดสินค้า"]);const retail=Number(text(r,["Retail Price","retail_price","ราคาปลีก"]));const member=Number(text(r,["Member Price","member_price","ราคาสมาชิก"]));const activeText=text(r,["Active","active","Status","สถานะ"]);const isActive=!["inactive","false","0","ปิด"].includes(activeText.toLowerCase());const updatedAt=text(r,["Updated At","updated_at","วันที่อัพเดต"]);
 if(!sku||!model||!color||!power||!Number.isFinite(retail)||!Number.isFinite(member))throw new Error("ข้อมูลจำเป็นไม่ครบ");
 let {data:product}=await s.from("products").select("id").eq("model_name",model).maybeSingle();if(!product){const x=await s.from("products").insert({model_name:model,category,product_updated_at:updatedAt?new Date(updatedAt).toISOString():new Date().toISOString(),is_active:isActive}).select("id").single();if(x.error)throw new Error(x.error.message);product=x.data;}else await s.from("products").update({category,product_updated_at:updatedAt?new Date(updatedAt).toISOString():new Date().toISOString(),...(isActive?{is_active:true}:{})}).eq("id",product.id);
 let {data:pc}=await s.from("product_colors").select("id").eq("product_id",product.id).eq("color_name",color).maybeSingle();if(!pc){const x=await s.from("product_colors").insert({product_id:product.id,color_name:color,is_active:true}).select("id").single();if(x.error)throw new Error(x.error.message);pc=x.data;}else{await s.from("product_colors").update({is_active:true,updated_at:new Date().toISOString()}).eq("id",pc.id);}
 const {data:existing}=await s.from("product_variants").select("id").eq("sku",sku).maybeSingle();if(existing){const x=await s.from("product_variants").update({product_id:product.id,color_id:pc.id,power,retail_price:retail,member_price:member,product_type:productType,is_orderable:isActive,variant_updated_at:new Date().toISOString()}).eq("id",existing.id);if(x.error)throw new Error(x.error.message);updated++;}else{const x=await s.from("product_variants").insert({product_id:product.id,color_id:pc.id,sku,power,retail_price:retail,member_price:member,product_type:productType,is_orderable:isActive}).select("id").single();if(x.error)throw new Error(x.error.message);await s.from("inventory_balances").insert({variant_id:x.data.id});created++;}
 }catch(e){errors.push({row:i+2,error:e instanceof Error?e.message:String(e)})}}
 const {data:allProducts}=await s.from("products").select("id"); for(const p of allProducts??[]){const {count}=await s.from("product_variants").select("id",{count:"exact",head:true}).eq("product_id",p.id).eq("is_orderable",true);await s.from("products").update({is_active:(count??0)>0,product_updated_at:new Date().toISOString()}).eq("id",p.id);} return NextResponse.json({success:true,created,updated,errors});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"นำเข้าสินค้าไม่สำเร็จ"},{status:500})}}
